HUB-828 - Fixing JSONAPI regression related to HUB-804 ( https://github.com/UH-StudentServices/student_guide/pull/383/files ).
Anonynous visitors would get a fatal error at https://studies.helsinki.fi/ohjeet/api/v1/degree-programme?_format=json :
LogicException: The controller result claims to be providing relevant cache metadata, but leaked metadata was detected. Please ensure you are not rendering content too early. Returned object class: Drupal\rest\ResourceResponse. in Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->wrapControllerExecutionInRenderContext() (line 154 of /var/www/html/build/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php).

Disablong access check permission is the simple fix here, and is secure because the query is only fetching node counts.

More info:
https://drupal.stackexchange.com/questions/251864/logicexception-the-controller-result-claims-to-be-providing-relevant-cache-meta
https://drupal.stackexchange.com/questions/258378/how-do-i-add-cacheablemetadata-to-an-array-im-returning-in-a-rest-resource
https://www.lullabot.com/articles/early-rendering-a-lesson-in-debugging-drupal-8